### ISSUE TITLE
Vagrant Konfiguration und Files wurden mit dem letzten Commit gelöscht!

### ISSUE THREAD

**Issue by twerthmueller** [swissredcross/src-web-dev-environment#1]
Die Vagrant Konfiguration wurde mit dem Commit 53e9498cdf7694b05be44a3a68f71ff9107483f8 gelöscht.

Bitte wieder herstellen.

Danke!
Thomas

**Comment by blazingarrow** [comment]
Hallo Thomas

Merci für den Hinweis und sorry für den Fehler. Ich habe die Konfiguration mit 515134a196e11dc71f7cf821162cd3839e933364 wieder hergestellt.
