### ISSUE TITLE
Upload Filesize weiter erhöhen

### ISSUE THREAD

**Issue by twerthmueller** [swissredcross/src-web-dev-environment#3]
Um einen DB Dump über Adminer direkt einspielen zu können, wäre ein Wert von 250M optimal.

upload_max_filesize: 250M

Natürlich kann man den Import auch direkt auf der VM machen.

**Comment by blazingarrow** [comment]
wir arbeiten eigentlich nur über Shell, ich kann das für euch aber auch einrichten, falls ihr Adminer wirklich benötigt?

**Comment by twerthmueller** [comment]
Nicht zwingend notwendig. Redcross muss ich von der Grösse her so oder so über Shell machen.
