### ISSUE TITLE
Provisioning Apache Virtual Hosts Problem

### ISSUE THREAD

**Issue by twerthmueller** [swissredcross/src-web-dev-environment#6]
Ich habe die VM kpl. neu aufgesetzt. Dach den Provisioning stehen die Seiten aber nicht zur Verfügung. Es erscheint immer die Standard-PuPHPet Seite. Die Server-Aliase wie zum Beispiel www.redcross.ch.srkcrs habe ich im Hosts-File eingetragen. Auch die V-Host Konfigurationen scheinen generiert worden zu sein.

Ich sehe in der Konfiguration nicht gleich wo die Problematik liegt. Hattet ihr dieses Problem nicht?

**Comment by twerthmueller** [comment]
Sehe das Problem, läuft auf Port 443. Das war das Problem.

**Comment by twerthmueller** [comment]
Bitte in Doku aufnehmen.

**Comment by blazingarrow** [comment]
Merci
